<?php

namespace ServiceBundle\Repository\BusinessDirectory;

/**
 * BusinessDirectoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessDirectoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get Business Directory By Keyword
     *
     * @param String $Keyword
     * @return Query|null
     */
    public function findByKeyword($Keyword)
    {
        return $this->createQueryBuilder('bd')
              ->select("bd.id, bd.companyName, bd.companyAddress, bd.longitude, bd.latitude , bd.sector as sectorName")
              ->where('bd.enabled = 1')
              ->orWhere('bd.companyName like :Keyword')
              ->orWhere('bd.companyAddress like :Keyword')
              ->orWhere('bd.longitude like :Keyword')
              ->orWhere('bd.latitude like :Keyword')
              ->orWhere('bd.sector like :Keyword')
              ->setParameter('Keyword', $Keyword)
              ->getQuery()
              ;
    }

    /**
     * Get all by Month
     *
     * @return array
     */
    public function findAllByMonth()
    {
        return $this->createQueryBuilder('bd')
                  ->select("count(bd) as value, DATE_FORMAT(bd.created ,'%m/%Y') as name")
                  ->groupBy('name')
                  ->getQuery()
                  ->getResult();
    }

    /**
     * count all
     *
     * @return int
     */
    public function countAll()
    {
        return $this->createQueryBuilder('bd')
        ->select("COUNT(bd)")
        ->getQuery()
        ->getSingleScalarResult();
    }
}
