<?php

namespace ServiceBundle\Repository\UserCV;

/**
 * InterestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterestsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get Interests By User
     *
     * @param User $user
     * @return Query|null
     */
    public function findByUser($user)
    {
        return $this->createQueryBuilder('h')
            ->join('h.users', 'user')
            ->where('user.id = :id')
            ->setParameter('id', $user->getId())
            ->getQuery()
            ->getResult()
            ;
    }

    /**
     * Get Interests
     *
     * @return Query|null
     */
    public function findAllHobbies()
    {
        return $this->createQueryBuilder('h')
            ->getQuery()
            ;
    }

}
