<?php

namespace ServiceBundle\Repository\UserCV;

/**
 * Portfolios Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolioRepository extends \Doctrine\ORM\EntityRepository
{
}
