<?php

namespace ServiceBundle\Repository\UserCV;

/**
 * socialMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
