<?php

namespace ServiceBundle\Repository\Administration;

/**
 * AlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get Alerts By user
     *
     * @param /ServiceBundle/Entity/UserCV/User $user
     * @return Query|null
     */
    public function findByUser($user)
    {
        return $this->createQueryBuilder('alert')
              ->select("alert.id, alert.title, alert.description, alert.type, alert.updated")
              ->join('alert.users', 'user')
              ->orWhere('user.id like :user')
              ->setParameter('user', $user->getId())
              ->orderBy('alert.id', 'desc')
              ->getQuery()
              ;
    }

    /**
     * Get Alerts By user
     *
     * @param /ServiceBundle/Entity/UserCV/User $user
     * @param int $limit
     * @return Query|null
     */
    public function findByUserLimit($user, $limit)
    {
        return $this->createQueryBuilder('alert')
              ->select("alert.id, alert.title, alert.description, alert.type, alert.updated")
              ->join('alert.users', 'user')
              ->orWhere('user.id like :user')
              ->setParameter('user', $user->getId())
              ->orderBy('alert.id', 'desc')
              ->setMaxResults($limit)
              ->getQuery()
              ->getResult()
              ;
    }
}
