<?php

namespace ServiceBundle\Repository\Administration;

/**
 * ContactUSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactUSRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * count all
     *
     * @return int
     */
    public function countAll()
    {
        return $this->createQueryBuilder('c')
                    ->select("COUNT(c)")
                    ->getQuery()
                    ->getSingleScalarResult();
    }
}
