<?php

namespace ServiceBundle\Repository;

/**
 * BusinessDirectoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessDirectoryRepository extends \Doctrine\ORM\EntityRepository
{
}
