<?php

namespace ServiceBundle\Repository\User;

/**
 * User Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get Users By Keyword
     *
     * @param String $Keyword
     * @return Query|null
     */
    public function findByKeyword($Keyword)
    {
        return $this->createQueryBuilder('user')
              ->select("partial user.{id, imageName, username, firstName, lastName, phone, email, summary, currentPosition}")
              ->where('user.username like :Keyword')
              ->orWhere('user.firstName like :Keyword')
              ->orWhere('user.lastName like :Keyword')
              ->orWhere('user.phone like :Keyword')
              ->orWhere('user.email like :Keyword')
              ->orWhere('user.summary like :Keyword')
              ->orWhere('user.currentPosition like :Keyword')
              ->orWhere('user.country like :Keyword')
              ->orWhere('user.codeZIP like :Keyword')
              ->orWhere('user.address like :Keyword')
              ->setParameter('Keyword', "%{$Keyword}%")
              ->getQuery()
              ;
    }

    /**
     * count all
     *
     * @return int
     */
    public function countAll()
    {
        return $this->createQueryBuilder('u')
        ->select("COUNT(u)")
        ->getQuery()
        ->getSingleScalarResult();
    }

    /**
     * Get all by Month
     *
     * @return array
     */
    public function findAllByMonth()
    {
        return $this->createQueryBuilder('u')
                  ->select("count(u) as value, DATE_FORMAT(u.created ,'%m/%Y') as name")
                  ->groupBy('name')
                  ->getQuery()
                  ->getResult();
    }
}
